CREATE ROLE demo2 WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:Z74vP6pi0WChZx5bHS6B4A==$Xz/ae7mp4xvdQ/jjgSffMPWt+RhpcVPoe7tmHdBRZnE=:+aH9tVB55kCTLThMBkGFyiPSPSwhR89y5idXs1ojhxk=';
  
  CREATE DATABASE demo
    WITH
    OWNER = demo2
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
    
CREATE ROLE demo WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:Z74vP6pi0WChZx5bHS6B4A==$Xz/ae7mp4xvdQ/jjgSffMPWt+RhpcVPoe7tmHdBRZnE=:+aH9tVB55kCTLThMBkGFyiPSPSwhR89y5idXs1ojhxk=';

CREATE DATABASE demo
    WITH
    OWNER = demo
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

DROP DATABASE demo;
DROP ROLE demo;

COMMIT;
