package com.example.demo.entity;

import java.time.LocalDate;

//import jakarta.validation.constraints.Email;
//import jakarta.validation.constraints.NotBlank;
//import jakarta.validation.constraints.Pattern;


public class Personalinfotable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.businesscardid
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private Integer businesscardid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.createdate
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private LocalDate createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.name
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.companyid
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private Integer companyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.department
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.post
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private String post;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.address
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.tel
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.mail
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private String mail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.projecttitle
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private String projecttitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personalinfotable.remarks
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	private String remarks;
	


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.businesscardid
	 * @return  the value of personalinfotable.businesscardid
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public Integer getBusinesscardid() {
		return businesscardid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.businesscardid
	 * @param businesscardid  the value for personalinfotable.businesscardid
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setBusinesscardid(Integer businesscardid) {
		this.businesscardid = businesscardid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.createdate
	 * @return  the value of personalinfotable.createdate
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public LocalDate getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.createdate
	 * @param createdate  the value for personalinfotable.createdate
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setCreatedate(LocalDate createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.name
	 * @return  the value of personalinfotable.name
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.name
	 * @param name  the value for personalinfotable.name
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.companyid
	 * @return  the value of personalinfotable.companyid
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public Integer getCompanyid() {
		return companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.companyid
	 * @param companyid  the value for personalinfotable.companyid
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setCompanyid(Integer companyid) {
		this.companyid = companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.department
	 * @return  the value of personalinfotable.department
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.department
	 * @param department  the value for personalinfotable.department
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setDepartment(String department) {
		this.department = department == null ? null : department.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.post
	 * @return  the value of personalinfotable.post
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public String getPost() {
		return post;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.post
	 * @param post  the value for personalinfotable.post
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setPost(String post) {
		this.post = post == null ? null : post.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.address
	 * @return  the value of personalinfotable.address
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.address
	 * @param address  the value for personalinfotable.address
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.tel
	 * @return  the value of personalinfotable.tel
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.tel
	 * @param tel  the value for personalinfotable.tel
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.mail
	 * @return  the value of personalinfotable.mail
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.mail
	 * @param mail  the value for personalinfotable.mail
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setMail(String mail) {
		this.mail = mail == null ? null : mail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.projecttitle
	 * @return  the value of personalinfotable.projecttitle
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public String getProjecttitle() {
		return projecttitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.projecttitle
	 * @param projecttitle  the value for personalinfotable.projecttitle
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setProjecttitle(String projecttitle) {
		this.projecttitle = projecttitle == null ? null : projecttitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personalinfotable.remarks
	 * @return  the value of personalinfotable.remarks
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personalinfotable.remarks
	 * @param remarks  the value for personalinfotable.remarks
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}
}