package com.example.demo.entity;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class PersonalinfotableExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public PersonalinfotableExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBusinesscardidIsNull() {
			addCriterion("businesscardid is null");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidIsNotNull() {
			addCriterion("businesscardid is not null");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidEqualTo(Integer value) {
			addCriterion("businesscardid =", value, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidNotEqualTo(Integer value) {
			addCriterion("businesscardid <>", value, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidGreaterThan(Integer value) {
			addCriterion("businesscardid >", value, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidGreaterThanOrEqualTo(Integer value) {
			addCriterion("businesscardid >=", value, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidLessThan(Integer value) {
			addCriterion("businesscardid <", value, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidLessThanOrEqualTo(Integer value) {
			addCriterion("businesscardid <=", value, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidIn(List<Integer> values) {
			addCriterion("businesscardid in", values, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidNotIn(List<Integer> values) {
			addCriterion("businesscardid not in", values, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidBetween(Integer value1, Integer value2) {
			addCriterion("businesscardid between", value1, value2, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andBusinesscardidNotBetween(Integer value1, Integer value2) {
			addCriterion("businesscardid not between", value1, value2, "businesscardid");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createdate is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createdate is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(LocalDate value) {
			addCriterion("createdate =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(LocalDate value) {
			addCriterion("createdate <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(LocalDate value) {
			addCriterion("createdate >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(LocalDate value) {
			addCriterion("createdate >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(LocalDate value) {
			addCriterion("createdate <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(LocalDate value) {
			addCriterion("createdate <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<LocalDate> values) {
			addCriterion("createdate in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<LocalDate> values) {
			addCriterion("createdate not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(LocalDate value1, LocalDate value2) {
			addCriterion("createdate between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(LocalDate value1, LocalDate value2) {
			addCriterion("createdate not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCompanyidIsNull() {
			addCriterion("companyid is null");
			return (Criteria) this;
		}

		public Criteria andCompanyidIsNotNull() {
			addCriterion("companyid is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyidEqualTo(Integer value) {
			addCriterion("companyid =", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidNotEqualTo(Integer value) {
			addCriterion("companyid <>", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidGreaterThan(Integer value) {
			addCriterion("companyid >", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidGreaterThanOrEqualTo(Integer value) {
			addCriterion("companyid >=", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidLessThan(Integer value) {
			addCriterion("companyid <", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidLessThanOrEqualTo(Integer value) {
			addCriterion("companyid <=", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidIn(List<Integer> values) {
			addCriterion("companyid in", values, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidNotIn(List<Integer> values) {
			addCriterion("companyid not in", values, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidBetween(Integer value1, Integer value2) {
			addCriterion("companyid between", value1, value2, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidNotBetween(Integer value1, Integer value2) {
			addCriterion("companyid not between", value1, value2, "companyid");
			return (Criteria) this;
		}

		public Criteria andDepartmentIsNull() {
			addCriterion("department is null");
			return (Criteria) this;
		}

		public Criteria andDepartmentIsNotNull() {
			addCriterion("department is not null");
			return (Criteria) this;
		}

		public Criteria andDepartmentEqualTo(String value) {
			addCriterion("department =", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotEqualTo(String value) {
			addCriterion("department <>", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentGreaterThan(String value) {
			addCriterion("department >", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
			addCriterion("department >=", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentLessThan(String value) {
			addCriterion("department <", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentLessThanOrEqualTo(String value) {
			addCriterion("department <=", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentLike(String value) {
			addCriterion("department like", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotLike(String value) {
			addCriterion("department not like", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentIn(List<String> values) {
			addCriterion("department in", values, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotIn(List<String> values) {
			addCriterion("department not in", values, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentBetween(String value1, String value2) {
			addCriterion("department between", value1, value2, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotBetween(String value1, String value2) {
			addCriterion("department not between", value1, value2, "department");
			return (Criteria) this;
		}

		public Criteria andPostIsNull() {
			addCriterion("post is null");
			return (Criteria) this;
		}

		public Criteria andPostIsNotNull() {
			addCriterion("post is not null");
			return (Criteria) this;
		}

		public Criteria andPostEqualTo(String value) {
			addCriterion("post =", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostNotEqualTo(String value) {
			addCriterion("post <>", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostGreaterThan(String value) {
			addCriterion("post >", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostGreaterThanOrEqualTo(String value) {
			addCriterion("post >=", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostLessThan(String value) {
			addCriterion("post <", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostLessThanOrEqualTo(String value) {
			addCriterion("post <=", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostLike(String value) {
			addCriterion("post like", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostNotLike(String value) {
			addCriterion("post not like", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostIn(List<String> values) {
			addCriterion("post in", values, "post");
			return (Criteria) this;
		}

		public Criteria andPostNotIn(List<String> values) {
			addCriterion("post not in", values, "post");
			return (Criteria) this;
		}

		public Criteria andPostBetween(String value1, String value2) {
			addCriterion("post between", value1, value2, "post");
			return (Criteria) this;
		}

		public Criteria andPostNotBetween(String value1, String value2) {
			addCriterion("post not between", value1, value2, "post");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andTelIsNull() {
			addCriterion("tel is null");
			return (Criteria) this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("tel is not null");
			return (Criteria) this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("tel =", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("tel <>", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("tel >", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("tel >=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("tel <", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("tel <=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("tel like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("tel not like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelIn(List<String> values) {
			addCriterion("tel in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotIn(List<String> values) {
			addCriterion("tel not in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("tel between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("tel not between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andMailIsNull() {
			addCriterion("mail is null");
			return (Criteria) this;
		}

		public Criteria andMailIsNotNull() {
			addCriterion("mail is not null");
			return (Criteria) this;
		}

		public Criteria andMailEqualTo(String value) {
			addCriterion("mail =", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailNotEqualTo(String value) {
			addCriterion("mail <>", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailGreaterThan(String value) {
			addCriterion("mail >", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailGreaterThanOrEqualTo(String value) {
			addCriterion("mail >=", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailLessThan(String value) {
			addCriterion("mail <", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailLessThanOrEqualTo(String value) {
			addCriterion("mail <=", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailLike(String value) {
			addCriterion("mail like", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailNotLike(String value) {
			addCriterion("mail not like", value, "mail");
			return (Criteria) this;
		}

		public Criteria andMailIn(List<String> values) {
			addCriterion("mail in", values, "mail");
			return (Criteria) this;
		}

		public Criteria andMailNotIn(List<String> values) {
			addCriterion("mail not in", values, "mail");
			return (Criteria) this;
		}

		public Criteria andMailBetween(String value1, String value2) {
			addCriterion("mail between", value1, value2, "mail");
			return (Criteria) this;
		}

		public Criteria andMailNotBetween(String value1, String value2) {
			addCriterion("mail not between", value1, value2, "mail");
			return (Criteria) this;
		}

		public Criteria andProjecttitleIsNull() {
			addCriterion("projecttitle is null");
			return (Criteria) this;
		}

		public Criteria andProjecttitleIsNotNull() {
			addCriterion("projecttitle is not null");
			return (Criteria) this;
		}

		public Criteria andProjecttitleEqualTo(String value) {
			addCriterion("projecttitle =", value, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleNotEqualTo(String value) {
			addCriterion("projecttitle <>", value, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleGreaterThan(String value) {
			addCriterion("projecttitle >", value, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleGreaterThanOrEqualTo(String value) {
			addCriterion("projecttitle >=", value, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleLessThan(String value) {
			addCriterion("projecttitle <", value, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleLessThanOrEqualTo(String value) {
			addCriterion("projecttitle <=", value, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleLike(String value) {
			addCriterion("projecttitle like", value, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleNotLike(String value) {
			addCriterion("projecttitle not like", value, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleIn(List<String> values) {
			addCriterion("projecttitle in", values, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleNotIn(List<String> values) {
			addCriterion("projecttitle not in", values, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleBetween(String value1, String value2) {
			addCriterion("projecttitle between", value1, value2, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andProjecttitleNotBetween(String value1, String value2) {
			addCriterion("projecttitle not between", value1, value2, "projecttitle");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNull() {
			addCriterion("remarks is null");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNotNull() {
			addCriterion("remarks is not null");
			return (Criteria) this;
		}

		public Criteria andRemarksEqualTo(String value) {
			addCriterion("remarks =", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotEqualTo(String value) {
			addCriterion("remarks <>", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThan(String value) {
			addCriterion("remarks >", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThanOrEqualTo(String value) {
			addCriterion("remarks >=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThan(String value) {
			addCriterion("remarks <", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThanOrEqualTo(String value) {
			addCriterion("remarks <=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLike(String value) {
			addCriterion("remarks like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotLike(String value) {
			addCriterion("remarks not like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksIn(List<String> values) {
			addCriterion("remarks in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotIn(List<String> values) {
			addCriterion("remarks not in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksBetween(String value1, String value2) {
			addCriterion("remarks between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotBetween(String value1, String value2) {
			addCriterion("remarks not between", value1, value2, "remarks");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personalinfotable
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 16 10:43:26 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}