package com.example.demo.mapper;

import com.example.demo.entity.Companytable;
import com.example.demo.entity.CompanytableExample;
//import com.example.demo.entity.Personalinfotable;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
//import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Options;


@Mapper
public interface CompanytableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    long countByExample(CompanytableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    int deleteByExample(CompanytableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    int deleteByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    int insert(Companytable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    @Options
    int insertSelective(Companytable string);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    List<Companytable> selectByExample(CompanytableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    Companytable selectByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    int updateByExampleSelective(@Param("row") Companytable row, @Param("example") CompanytableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    int updateByExample(@Param("row") Companytable row, @Param("example") CompanytableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    int updateByPrimaryKeySelective(Companytable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companytable
     *
     * @mbg.generated Thu Nov 30 11:47:25 JST 2023
     */
    int updateByPrimaryKey(Companytable row);
    
    //  すべての名刺を検索
//    @Select("SELECT * FROM Companytable")
    @Options
	List<Companytable> selectAll();

	//  idが一致するものを検索
	Companytable findById(int companyId);

	//	テーブルのデータと部分一致するものを検索
	List<Companytable> mySelectByExample(String keyword);
	
}