package com.example.demo.mapper;

import com.example.demo.entity.Personalinfotable;
import com.example.demo.entity.PersonalinfotableExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PersonalinfotableMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	long countByExample(PersonalinfotableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	int deleteByExample(PersonalinfotableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	int deleteByPrimaryKey(Integer businesscardid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	int insert(Personalinfotable row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	@Options
	int insertSelective(Personalinfotable row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	List<Personalinfotable> selectByExample(PersonalinfotableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	Personalinfotable selectByPrimaryKey(Integer businesscardid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Personalinfotable row,
			@Param("example") PersonalinfotableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	int updateByExample(@Param("row") Personalinfotable row, @Param("example") PersonalinfotableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	int updateByPrimaryKeySelective(Personalinfotable row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personalinfotable
	 * @mbg.generated  Thu Nov 30 11:47:25 JST 2023
	 */
	int updateByPrimaryKey(Personalinfotable row);

	//  すべての名刺を検索
	List<Personalinfotable> selectAll();

	//  idが一致するものを検索
	Personalinfotable findById(@Param("businesscardid") int businesscardid);

	//	テーブルのデータと部分一致するものを検索
	List<Personalinfotable> mySelectByExample(String keyword);
	
	
}